### ISSUE TITLE
output dosn't show up

### ISSUE THREAD

**Issue by SabraHashemi** [alitourani/yolo-license-plate-detection#3]
i get result (for video) such below in cmd  but in the window with deep ... title ,it's all gray image 
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)
out.shape :  (507, 6)
out.shape :  (2028, 6)
out.shape :  (8112, 6)

**Comment by SabraHashemi** [comment]
and also for a 5 mins video it lasts for 60 mins (cmd outputs).

any suggestion for speed up?

**Comment by shalini264** [comment]
Same issue.

**Comment by shalini264** [comment]
@sabrabano0 Did you come up with any solution now?

**Comment by SabraHashemi** [comment]
@shalini264  yeah i solved this, but i can't  remember  solution to this right now, if you give me more detail maybe i  figure out

**Comment by alitourani** [comment]
@sabrabano0 thanks for the contribution and sorry for the late response.
Could you prepare some more details about the problem so that I can check and update the solution?

**Comment by shalini264** [comment]
@sabrabano0  i did it. Thanks anyways!

**Comment by SabraHashemi** [comment]
> @sabrabano0 i did it. Thanks anyways!
Well done, 
also it is so great if you write the solution here for future  engineers
good luck.

**Comment by shalini264** [comment]
In case of videos, if we detect license plate frame by frame. Though its time consuming but it works.
